FROM mcr.microsoft.com/devcontainers/dotnet:2-10.0-noble

# [Optional] Uncomment this section to install additional OS packages.
RUN apt update -y && apt upgrade -y

# RUN sh -c 'curl -LsSf https://astral.sh/uv/install.sh | sh' 
# [Optional] Uncomment this line to install global node packages.
# RUN su vscode -c "source /usr/local/share/nvm/nvm.sh && npm install -g <your-package-here>" 2>&1